version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "queue-project-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h7ghzqf38wow"
s3_prefix = "queue-project-app"
region = "us-east-1"
profile = "pv"
capabilities = "CAPABILITY_IAM"

